name: Build Native

on: workflow_dispatch

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install gcc-multilib
        run: sudo apt install gcc-multilib

      - name: CMake configure (x86)
        run: cmake -DCMAKE_CXX_FLAGS=-m32 -B release-x86 GenerateBindings -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build (x86)
        run: ninja -C release-x86

      - name: Archive build result (x86)
        uses: actions/upload-artifact@v4
        with:
          name: native-linux-x86
          path: release-x86/libyoga.so

      - name: CMake configure (x64)
        run: cmake -B release-x64 -G Ninja GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build (x64)
        run: ninja -C release-x64

      - name: Archive build result (x64)
        uses: actions/upload-artifact@v4
        with:
          name: native-linux-x64
          path: release-x64/libyoga.so

  linux-arm64:
    name: Linux Arm64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
  
      - name: CMake configure
        run: cmake -B release -G Ninja GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: ninja -C release

      - name: Archive build result
        uses: actions/upload-artifact@v4
        with:
          name: native-linux-arm64
          path: release/libyoga.so

  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: CMake configure (x86)
        run: cmake -G "Visual Studio 17 2022" -A Win32 -B release-x86 GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build (x86)
        run: cmake --build release-x86 --config Release

      - name: Archive build result (x86)
        uses: actions/upload-artifact@v4
        with:
          name: native-win-x86
          path: release-x86/Release/yoga.dll

      - name: CMake configure (x64)
        run: cmake -G "Visual Studio 17 2022" -B release-x64 GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build (x64)
        run: cmake --build release-x64 --config Release

      - name: Archive build result (x64)
        uses: actions/upload-artifact@v4
        with:
          name: native-win-x64
          path: release-x64/Release/yoga.dll

      - name: CMake configure (arm64)
        run: cmake -G "Visual Studio 17 2022" -A ARM64 -B release-arm64 GenerateBindings -DCMAKE_BUILD_TYPE=Release

      - name: Build (arm64)
        run: cmake --build release-arm64 --config Release

      - name: Archive build result (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: native-win-arm64
          path: release-arm64/Release/yoga.dll
  
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: brew install ninja

      - name: CMake configure (arm64)
        run: cmake -G Ninja -B release-arm64 GenerateBindings -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

      - name: Build (arm64)
        run: ninja -C release-arm64

      - name: Archive build result (arm64)
        uses: actions/upload-artifact@v4
        with:
          name: native-osx-arm64
          path: release-arm64/libyoga.dylib

      - name: CMake configure (x64)
        run: cmake -G Ninja -B release-x64 GenerateBindings -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="x86_64" -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0

      - name: Build (x64)
        run: ninja -C release-x64

      - name: Archive build result (x64)
        uses: actions/upload-artifact@v4
        with:
          name: native-osx-x64
          path: release-x64/libyoga.dylib
